# User configuration
title:  Samsir
description:  > # this means to ignore newlines until "baseurl:"
url:  https://samsir.github.io/rumah # the base hostname & protocol for your site

# This should be the same author as first entry in `_data/authors.yml`
author:
  name: Samsir

# Fallback image and color
image:  https://samsir.github.io/rumah/assets/img/brand.png
color:  '#14ac6c'

# Site Brand
brand: https://samsir.github.io/rumah/assets/img/brand.svg

# Set your Google Analytics id to receive `pageview` events.
# google_analytics: 

# Setting a disqus shortname will enable the comment section on pages with `comments: true` in the front matter
# disqus_shortname: samsiralam

# This text will appear in the footer. Markdown enabled.
copyright:  'samsir'

# Format of the permalinks
permalink:  pretty

# Pagination configuration
paginate: 5
paginate_path:  'blog/page/:num'

# Set to true when building with the `--lsi` option
# See: https://jekyllrb.com/docs/variables/#site-variables
# use_lsi:             true

# Collections
collections:
  pages:
    permalink: /insight/:path/
    output: true
  posts:
    permalink: /post/:title/
    output: true
  archives:
    permalink: /:path/
    output: true
    categories:
      output: true
    tags:
      output: true

# Plugin
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Minified stylesheet
sass:
  style:  compressed

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
